version: '3'

services:
  web:
    image: inviti
    build:
      context: .
      dockerfile: ./docker/production/app/Dockerfile
    env_file:
      .production.new.env
    command: bin/web
    volumes:
      - gems:/gems
      - ./storage:/storage
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"


  crono:
    image: inviti
    environment:
      SILENCE_AR_LOGGER: "yes"
    env_file:
      .production.new.env
    command: bin/crono
    volumes:
      - gems:/gems
      - ./storage:/storage
    depends_on:
      - db
      - redis


  worker:
    image: inviti
    env_file:
      .production.new.env
    command: bin/worker
    volumes:
      - gems:/gems
      - ./storage:/storage
    depends_on:
      - db
      - redis


  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis



volumes:
  gems: {}
  storage: {}
  postgres_data: {}
