version: '3'

# networks:


services:
  web:
    build:
      context: .
      dockerfile: ./docker/staging/app/Dockerfile
    env_file:
      .staging.env
    command: bin/web
    volumes:
      - gems:/gems
      - storage:/storage
    depends_on:
      - db
      - redis
    # networks:
    #   - host

  check_emails:
    build:
      context: .
      dockerfile: ./docker/staging/app/Dockerfile
    env_file:
      .staging.env
    command: bin/check_emails
    volumes:
      - gems:/gems
    depends_on:
      - db
      - redis
      - web
    # networks:
    #   - host

  worker:
    build:
      context: .
      dockerfile: ./docker/staging/app/Dockerfile
    env_file:
      .staging.env
    command: bin/worker
    volumes:
      - gems:/gems
      - storage:/storage
    depends_on:
      - db
      - redis
      - web
    # networks:
    #   - host


  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - host

  redis:
    image: redis
    # networks:
    #   - host

  nginx:
    build:
      context: .
      dockerfile: ./docker/staging/nginx/Dockerfile
    depends_on:
      - web
    restart: on-failure
    volumes:
      - ./ssl_certificates:/etc/nginx/certs
    ports:
      - 443:443
    # networks:
    #   - host

volumes:
  gems: {}
  storage: {}
  postgres_data: {}

# docker-compose up -d
# docker-compose down

# docker-compose up -d --no-deps --build web

# Access the container:
#   docker exec -it midilab_web_1_e54a4bb5279f /bin/sh
