version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/app/Dockerfile
    env_file:
      .production.env
    command: bin/web
    volumes:
      - gems:/gems
      - ./storage:/storage
    depends_on:
      - db
      - redis
    extra_hosts:
      - "posta.arera.it:192.168.200.21"
      - "posta.arera.it:192.168.200.22"
      - "relay1.arera.it:192.168.0.251"
      - "relay2.arera.it:192.168.0.252"
      - "intranet.arera.it:192.168.170.4"


  crono:
    build:
      context: .
      dockerfile: ./docker/production/app/Dockerfile
    environment:
      SILENCE_AR_LOGGER: "yes"
    env_file:
      .production.env
    command: bin/crono
    volumes:
      - gems:/gems
      - ./storage:/storage
    depends_on:
      - db
      - redis
      # - web
    extra_hosts:
      - "posta.arera.it:192.168.200.21"
      - "posta.arera.it:192.168.200.22"
      - "relay1.arera.it:192.168.0.251"
      - "relay2.arera.it:192.168.0.252"
      - "intranet.arera.it:192.168.170.4"


  worker:
    build:
      context: .
      dockerfile: ./docker/production/app/Dockerfile
    env_file:
      .production.env
    command: bin/worker
    volumes:
      - gems:/gems
      - ./storage:/storage
    depends_on:
      - db
      - redis
      # - web
    extra_hosts:
      - "posta.arera.it:192.168.200.21"
      - "posta.arera.it:192.168.200.22"
      - "relay1.arera.it:192.168.0.251"
      - "relay2.arera.it:192.168.0.252"
      - "intranet.arera.it:192.168.170.4"


  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis


  nginx:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    depends_on:
      - web
    restart: on-failure
    volumes:
      - ./ssl_certificates:/etc/nginx/certs
    ports:
      - 443:443
      - 80:80
    extra_hosts:
      - "posta.arera.it:192.168.200.21"
      - "posta.arera.it:192.168.200.22"
      - "relay1.arera.it:192.168.0.251"
      - "relay2.arera.it:192.168.0.252"
      - "intranet.arera.it:192.168.170.4"


volumes:
  gems: {}
  storage: {}
  postgres_data: {}

# docker-compose up -d
# docker-compose down

# docker-compose up -d --no-deps --build web

# Access the container:
#   docker exec -it midilab_web_1_e54a4bb5279f /bin/sh
