version: '3'
volumes:
  postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/app/Dockerfile
    env_file:
      .production.env
    command: bin/web
    volumes:
      - gems:/gems
      - storage:/storage
    depends_on:
      - db
      - redis

  check_emails:
    build:
      context: .
      dockerfile: ./docker/production/app/Dockerfile
    env_file:
      .production.env
    command: bin/check_emails
    volumes:
      - gems:/gems
    depends_on:
      - db
      - web

  worker:
    build:
      context: .
      dockerfile: ./docker/production/app/Dockerfile
    env_file:
      .production.env
    command: bin/worker
    volumes:
      - gems:/gems
      - storage:/storage
    depends_on:
      - db
      - redis
      - web


  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis

  web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80

volumes:
  gems: {}
  storage: {}
  postgres_data: {}

# docker-compose up -d
# docker-compose down

# docker-compose up -d --no-deps --build web

# Access the container:
#   docker exec -it midilab_web_1_e54a4bb5279f /bin/sh
