default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: 15

test:
  <<: *default
  database: invt_test

development:
  <<: *default
  database: invt_development

production:
  <<: *default
  host: db
  database: invt_production
