default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: 5
  host: db

development:
  <<: *default
  database: invt_development

production:
  <<: *default
  database: invt_production
